device: 0
save_dir : 'log'
# seed: 3435

data:
  train_file: 'data/basque.standard.both/basque-standard-train.pkl'
  val_file: 'data/basque.standard.both/basque-standard-valid.pkl'
  test_file: 'data/basque.standard.both/basque-standard-test.pkl'
  vocab_type: 'max_size'
  vocab_size: 10000
  min_freq: 2


model:
  model_name: 'CPCFG'
  NT: 30
  T: 60
  s_dim: 256
  w_dim: 512
  h_dim: 512
  z_dim: 64
  mode: 'length'

train:
  batch_size: 4
  max_epoch: 20
  max_len: 40
  min_len: 0
  #whether to use curriculum learning stragegy.
  curriculum: 1
  start_len: 30
  increment: 1
  patience: 5
  clip: 3
  warmup_epoch: 3

test:
  batch_size: 8
  max_tokens: 100
  bucket: 32
  decode: 'mbr'
  sampler: 'batch'
  depth: 40
  eval_depth: True
  left_binarization: True
  right_binarization: True

optimizer:
  name: 'adam'
  lr: 0.001
  mu: 0.75
  nu: 0.999






