device: 0
save_dir : 'log'
# seed: 3435
pretrained_model: 'log/pretrained_cpcfg_nt30_t60_curriculum1/CPCFG2022-01-05-10_25_58/best.pt'

data:
  train_file: 'data/data.clean/english-train.pkl'
  val_file: 'data/data.clean/english-valid.pkl'
  test_file: 'data/data.clean/english-test.pkl'
  vocab_type: 'max_size'
  vocab_size: 10000
  min_freq: 2


model:
  model_name: 'CPCFG'
  NT: 30
  T: 60
  s_dim: 256
  w_dim: 512
  h_dim: 512
  z_dim: 64
  depth: 0
  fix_root: True
  fix_root_mlp: True

train:
  batch_size: 4
  max_epoch: 5
  max_len: 40
  #whether to use curriculum learning stragegy.
  curriculum: 1
  start_len: 35
  increment: 1
  patience: 5
  clip: 3


test:
  batch_size: 8
  max_tokens: 100
  bucket: 32
  decode: 'mbr'
  sampler: 'batch'

optimizer:
  name: 'adam'
  lr: 0.001
  mu: 0.75
  nu: 0.999






