device: 0
save_dir : 'log'
# seed: 3435

data:
  train_file: 'data/depth.cnf/english-depth-train.pkl'
  val_file: 'data/depth.cnf/english-depth-valid.pkl'
  test_file: 'data/depth.cnf/english-depth-test.pkl'
  vocab_type: 'max_size'
  vocab_size: 10000
  min_freq: 2


model:
  model_name: 'CPCFG'
  NT: 30
  T: 60
  s_dim: 256
  w_dim: 512
  h_dim: 512
  z_dim: 64
  depth: 0

train:
  batch_size: 4
  max_epoch: 10
  max_len: 40
  #whether to use curriculum learning stragegy.
  curriculum: 1
  start_len: 30
  increment: 1
  patience: 5
  clip: 3
  init_depth: 42
  min_depth: 32
  depth_curriculum: 'linear'
  warmup: 30000


test:
  batch_size: 8
  max_tokens: 100
  bucket: 32
  decode: 'mbr'
  sampler: 'batch'

optimizer:
  name: 'adam'
  lr: 0.001
  mu: 0.75
  nu: 0.999






